# Generated by Django 3.2.7 on 2021-09-24 16:18

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210923_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='McqProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('optiona', models.TextField(max_length=100)),
                ('optionb', models.TextField(max_length=100)),
                ('optionc', models.TextField(max_length=100)),
                ('optiond', models.TextField(max_length=100)),
                ('correct_ans', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='McqSubmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_output', models.IntegerField(default=0)),
                ('result', models.NullBooleanField(default=None)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.mcqproblems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('contest_link', models.CharField(max_length=1000)),
                ('overview', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('start_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('end_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('image_link', models.CharField(blank=True, default='/static/newtheme/img/test.jpeg', max_length=1000)),
                ('mcq_problems', models.ManyToManyField(blank=True, to='authentication.McqProblems')),
                ('participants', models.ManyToManyField(blank=True, to='authentication.Profile')),
            ],
        ),
    ]
