# Generated by Django 3.2.5 on 2021-09-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_chek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('When', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='chek',
        ),
    ]
